import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Navbar from "./Components/Common/Navbar";
import "./globals.css";
import Footer from "./Components/Common/Footer";
import ReduxProvider from "./ReduxProvider";

const jostSans = Jost({
  variable: "--font-jost-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jostSans.className} antialiased`}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
