import { Product } from "@/app/Types/Types";
import React from "react";
import ItemsLister from "../Common/ItemsLister";

export const allProducts: Product[] = [
  {
    _id: "1",
    userId: 101,
    id: 1,
    description: {
      player: "LeBron James",
      desc: "Official Lakers T-shirt, lightweight and breathable",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=1",
      back: "https://picsum.photos/400/600?random=2",
      left: "https://picsum.photos/400/600?random=3",
      right: "https://picsum.photos/400/600?random=4",
      model: "https://picsum.photos/400/600?random=5",
      modelFront: "https://picsum.photos/400/600?random=6",
      modelBack: "https://picsum.photos/400/600?random=7",
      modelLeft: "https://picsum.photos/400/600?random=8",
      modelRight: "https://picsum.photos/400/600?random=9",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 5, s: 10, m: 15, l: 20, xl: 10, xxl: 5 },
    price: 35,
    type: "T-shirt",
    materials: [
      { percentage: 80, materialName: "Cotton" },
      { percentage: 20, materialName: "Polyester" },
    ],
    details: ["Official NBA licensed", "Breathable fabric", "Machine washable"],
    washing: "Machine wash cold",
    name: "LeBron James Lakers Tee",
  },
  {
    _id: "2",
    userId: 102,
    id: 2,
    description: {
      player: "Stephen Curry",
      desc: "Golden State Warriors Hoodie, soft fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=10",
      back: "https://picsum.photos/400/600?random=11",
      left: "https://picsum.photos/400/600?random=12",
      right: "https://picsum.photos/400/600?random=13",
      model: "https://picsum.photos/400/600?random=14",
      modelFront: "https://picsum.photos/400/600?random=15",
      modelBack: "https://picsum.photos/400/600?random=16",
      modelLeft: "https://picsum.photos/400/600?random=17",
      modelRight: "https://picsum.photos/400/600?random=18",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 3, s: 12, m: 18, l: 25, xl: 12, xxl: 6 },
    price: 70,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Warm fleece inside", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Stephen Curry Warriors Hoodie",
  },
  {
    _id: "3",
    userId: 103,
    id: 3,
    description: {
      player: "Kevin Durant",
      desc: "Brooklyn Nets Jersey, lightweight performance fabric",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=19",
      back: "https://picsum.photos/400/600?random=20",
      left: "https://picsum.photos/400/600?random=21",
      right: "https://picsum.photos/400/600?random=22",
      model: "https://picsum.photos/400/600?random=23",
      modelFront: "https://picsum.photos/400/600?random=24",
      modelBack: "https://picsum.photos/400/600?random=25",
      modelLeft: "https://picsum.photos/400/600?random=26",
      modelRight: "https://picsum.photos/400/600?random=27",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 8, m: 16, l: 24, xl: 8, xxl: 4 },
    price: 85,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Moisture-wicking", "Lightweight"],
    washing: "Hand wash recommended",
    name: "Kevin Durant Nets Jersey",
  },
  {
    _id: "4",
    userId: 104,
    id: 4,
    description: {
      player: "Giannis Antetokounmpo",
      desc: "Milwaukee Bucks T-shirt, casual fit",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=28",
      back: "https://picsum.photos/400/600?random=29",
      left: "https://picsum.photos/400/600?random=30",
      right: "https://picsum.photos/400/600?random=31",
      model: "https://picsum.photos/400/600?random=32",
      modelFront: "https://picsum.photos/400/600?random=33",
      modelBack: "https://picsum.photos/400/600?random=34",
      modelLeft: "https://picsum.photos/400/600?random=35",
      modelRight: "https://picsum.photos/400/600?random=36",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 4, s: 9, m: 14, l: 22, xl: 10, xxl: 5 },
    price: 40,
    type: "T-shirt",
    materials: [
      { percentage: 70, materialName: "Cotton" },
      { percentage: 30, materialName: "Polyester" },
    ],
    details: ["Casual fit", "Soft material", "Machine washable"],
    washing: "Machine wash cold",
    name: "Giannis Bucks Tee",
  },
  {
    _id: "13",
    userId: 113,
    id: 13,
    description: {
      player: "Bradley Beal",
      desc: "Washington Wizards T-shirt, casual fit",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=37",
      back: "https://picsum.photos/400/600?random=38",
      left: "https://picsum.photos/400/600?random=39",
      right: "https://picsum.photos/400/600?random=40",
      model: "https://picsum.photos/400/600?random=41",
      modelFront: "https://picsum.photos/400/600?random=42",
      modelBack: "https://picsum.photos/400/600?random=43",
      modelLeft: "https://picsum.photos/400/600?random=44",
      modelRight: "https://picsum.photos/400/600?random=45",
    },
    date_added: Date.now(),
    isPromotion: true,
    sizes: { xs: 5, s: 10, m: 15, l: 20, xl: 10, xxl: 5 },
    price: 36,
    type: "T-shirt",
    materials: [
      { percentage: 80, materialName: "Cotton" },
      { percentage: 20, materialName: "Polyester" },
    ],
    details: ["Official NBA licensed", "Casual fit", "Machine washable"],
    washing: "Machine wash cold",
    name: "Bradley Beal Wizards Tee",
  },
  {
    _id: "14",
    userId: 114,
    id: 14,
    description: {
      player: "Donovan Mitchell",
      desc: "Cleveland Hoodie, soft fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=46",
      back: "https://picsum.photos/400/600?random=47",
      left: "https://picsum.photos/400/600?random=48",
      right: "https://picsum.photos/400/600?random=49",
      model: "https://picsum.photos/400/600?random=50",
      modelFront: "https://picsum.photos/400/600?random=51",
      modelBack: "https://picsum.photos/400/600?random=52",
      modelLeft: "https://picsum.photos/400/600?random=53",
      modelRight: "https://picsum.photos/400/600?random=54",
    },
    date_added: Date.now(),
    isPromotion: true,
    sizes: { xs: 3, s: 12, m: 18, l: 24, xl: 12, xxl: 6 },
    price: 72,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Warm fleece", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Donovan Mitchell Hoodie",
  },
  {
    _id: "15",
    userId: 115,
    id: 15,
    description: {
      player: "Devin Booker",
      desc: "Phoenix Suns Jersey, lightweight performance",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=55",
      back: "https://picsum.photos/400/600?random=56",
      left: "https://picsum.photos/400/600?random=57",
      right: "https://picsum.photos/400/600?random=58",
      model: "https://picsum.photos/400/600?random=59",
      modelFront: "https://picsum.photos/400/600?random=60",
      modelBack: "https://picsum.photos/400/600?random=61",
      modelLeft: "https://picsum.photos/400/600?random=62",
      modelRight: "https://picsum.photos/400/600?random=63",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 7, m: 15, l: 21, xl: 9, xxl: 3 },
    price: 88,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Breathable", "Moisture-wicking"],
    washing: "Hand wash recommended",
    name: "Devin Booker Suns Jersey",
  },
  {
    _id: "16",
    userId: 116,
    id: 16,
    description: {
      player: "CJ McCollum",
      desc: "Portland Trail Blazers T-shirt, casual",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=64",
      back: "https://picsum.photos/400/600?random=65",
      left: "https://picsum.photos/400/600?random=66",
      right: "https://picsum.photos/400/600?random=67",
      model: "https://picsum.photos/400/600?random=68",
      modelFront: "https://picsum.photos/400/600?random=69",
      modelBack: "https://picsum.photos/400/600?random=70",
      modelLeft: "https://picsum.photos/400/600?random=71",
      modelRight: "https://picsum.photos/400/600?random=72",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 4, s: 9, m: 14, l: 22, xl: 10, xxl: 5 },
    price: 39,
    type: "T-shirt",
    materials: [
      { percentage: 75, materialName: "Cotton" },
      { percentage: 25, materialName: "Polyester" },
    ],
    details: ["Casual fit", "Soft material", "Machine washable"],
    washing: "Machine wash cold",
    name: "CJ McCollum Blazers Tee",
  },
  {
    _id: "17",
    userId: 117,
    id: 17,
    description: {
      player: "Kyrie Irving",
      desc: "Brooklyn Nets Hoodie, warm fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=73",
      back: "https://picsum.photos/400/600?random=74",
      left: "https://picsum.photos/400/600?random=75",
      right: "https://picsum.photos/400/600?random=76",
      model: "https://picsum.photos/400/600?random=77",
      modelFront: "https://picsum.photos/400/600?random=78",
      modelBack: "https://picsum.photos/400/600?random=79",
      modelLeft: "https://picsum.photos/400/600?random=80",
      modelRight: "https://picsum.photos/400/600?random=81",
    },
    date_added: Date.now(),
    isPromotion: true,
    sizes: { xs: 3, s: 11, m: 17, l: 23, xl: 13, xxl: 7 },
    price: 74,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Soft fleece", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Kyrie Irving Nets Hoodie",
  },
  {
    _id: "18",
    userId: 118,
    id: 18,
    description: {
      player: "Julius Randle",
      desc: "New York Knicks Jersey, performance",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=82",
      back: "https://picsum.photos/400/600?random=83",
      left: "https://picsum.photos/400/600?random=84",
      right: "https://picsum.photos/400/600?random=85",
      model: "https://picsum.photos/400/600?random=86",
      modelFront: "https://picsum.photos/400/600?random=87",
      modelBack: "https://picsum.photos/400/600?random=88",
      modelLeft: "https://picsum.photos/400/600?random=89",
      modelRight: "https://picsum.photos/400/600?random=90",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 8, m: 16, l: 22, xl: 8, xxl: 4 },
    price: 86,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Lightweight", "Moisture-wicking"],
    washing: "Hand wash recommended",
    name: "Julius Randle Knicks Jersey",
  },
  {
    _id: "1",
    userId: 101,
    id: 1,
    description: {
      player: "LeBron James",
      desc: "Official Lakers T-shirt, lightweight and breathable",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=1",
      back: "https://picsum.photos/400/600?random=2",
      left: "https://picsum.photos/400/600?random=3",
      right: "https://picsum.photos/400/600?random=4",
      model: "https://picsum.photos/400/600?random=5",
      modelFront: "https://picsum.photos/400/600?random=6",
      modelBack: "https://picsum.photos/400/600?random=7",
      modelLeft: "https://picsum.photos/400/600?random=8",
      modelRight: "https://picsum.photos/400/600?random=9",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 5, s: 10, m: 15, l: 20, xl: 10, xxl: 5 },
    price: 35,
    type: "T-shirt",
    materials: [
      { percentage: 80, materialName: "Cotton" },
      { percentage: 20, materialName: "Polyester" },
    ],
    details: ["Official NBA licensed", "Breathable fabric", "Machine washable"],
    washing: "Machine wash cold",
    name: "LeBron James Lakers Tee",
  },
  {
    _id: "2",
    userId: 102,
    id: 2,
    description: {
      player: "Stephen Curry",
      desc: "Golden State Warriors Hoodie, soft fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=10",
      back: "https://picsum.photos/400/600?random=11",
      left: "https://picsum.photos/400/600?random=12",
      right: "https://picsum.photos/400/600?random=13",
      model: "https://picsum.photos/400/600?random=14",
      modelFront: "https://picsum.photos/400/600?random=15",
      modelBack: "https://picsum.photos/400/600?random=16",
      modelLeft: "https://picsum.photos/400/600?random=17",
      modelRight: "https://picsum.photos/400/600?random=18",
    },
    date_added: Date.now(),
    isPromotion: true,
    sizes: { xs: 3, s: 12, m: 18, l: 25, xl: 12, xxl: 6 },
    price: 70,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Warm fleece inside", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Stephen Curry Warriors Hoodie",
  },
  {
    _id: "3",
    userId: 103,
    id: 3,
    description: {
      player: "Kevin Durant",
      desc: "Brooklyn Nets Jersey, lightweight performance fabric",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=19",
      back: "https://picsum.photos/400/600?random=20",
      left: "https://picsum.photos/400/600?random=21",
      right: "https://picsum.photos/400/600?random=22",
      model: "https://picsum.photos/400/600?random=23",
      modelFront: "https://picsum.photos/400/600?random=24",
      modelBack: "https://picsum.photos/400/600?random=25",
      modelLeft: "https://picsum.photos/400/600?random=26",
      modelRight: "https://picsum.photos/400/600?random=27",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 8, m: 16, l: 24, xl: 8, xxl: 4 },
    price: 85,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Moisture-wicking", "Lightweight"],
    washing: "Hand wash recommended",
    name: "Kevin Durant Nets Jersey",
  },
  {
    _id: "4",
    userId: 104,
    id: 4,
    description: {
      player: "Giannis Antetokounmpo",
      desc: "Milwaukee Bucks T-shirt, casual fit",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=28",
      back: "https://picsum.photos/400/600?random=29",
      left: "https://picsum.photos/400/600?random=30",
      right: "https://picsum.photos/400/600?random=31",
      model: "https://picsum.photos/400/600?random=32",
      modelFront: "https://picsum.photos/400/600?random=33",
      modelBack: "https://picsum.photos/400/600?random=34",
      modelLeft: "https://picsum.photos/400/600?random=35",
      modelRight: "https://picsum.photos/400/600?random=36",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 4, s: 9, m: 14, l: 22, xl: 10, xxl: 5 },
    price: 40,
    type: "T-shirt",
    materials: [
      { percentage: 70, materialName: "Cotton" },
      { percentage: 30, materialName: "Polyester" },
    ],
    details: ["Casual fit", "Soft material", "Machine washable"],
    washing: "Machine wash cold",
    name: "Giannis Bucks Tee",
  },
  {
    _id: "13",
    userId: 113,
    id: 13,
    description: {
      player: "Bradley Beal",
      desc: "Washington Wizards T-shirt, casual fit",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=37",
      back: "https://picsum.photos/400/600?random=38",
      left: "https://picsum.photos/400/600?random=39",
      right: "https://picsum.photos/400/600?random=40",
      model: "https://picsum.photos/400/600?random=41",
      modelFront: "https://picsum.photos/400/600?random=42",
      modelBack: "https://picsum.photos/400/600?random=43",
      modelLeft: "https://picsum.photos/400/600?random=44",
      modelRight: "https://picsum.photos/400/600?random=45",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 5, s: 10, m: 15, l: 20, xl: 10, xxl: 5 },
    price: 36,
    type: "T-shirt",
    materials: [
      { percentage: 80, materialName: "Cotton" },
      { percentage: 20, materialName: "Polyester" },
    ],
    details: ["Official NBA licensed", "Casual fit", "Machine washable"],
    washing: "Machine wash cold",
    name: "Bradley Beal Wizards Tee",
  },
  {
    _id: "14",
    userId: 114,
    id: 14,
    description: {
      player: "Donovan Mitchell",
      desc: "Cleveland Hoodie, soft fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=46",
      back: "https://picsum.photos/400/600?random=47",
      left: "https://picsum.photos/400/600?random=48",
      right: "https://picsum.photos/400/600?random=49",
      model: "https://picsum.photos/400/600?random=50",
      modelFront: "https://picsum.photos/400/600?random=51",
      modelBack: "https://picsum.photos/400/600?random=52",
      modelLeft: "https://picsum.photos/400/600?random=53",
      modelRight: "https://picsum.photos/400/600?random=54",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 3, s: 12, m: 18, l: 24, xl: 12, xxl: 6 },
    price: 72,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Warm fleece", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Donovan Mitchell Hoodie",
  },
  {
    _id: "15",
    userId: 115,
    id: 15,
    description: {
      player: "Devin Booker",
      desc: "Phoenix Suns Jersey, lightweight performance",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=55",
      back: "https://picsum.photos/400/600?random=56",
      left: "https://picsum.photos/400/600?random=57",
      right: "https://picsum.photos/400/600?random=58",
      model: "https://picsum.photos/400/600?random=59",
      modelFront: "https://picsum.photos/400/600?random=60",
      modelBack: "https://picsum.photos/400/600?random=61",
      modelLeft: "https://picsum.photos/400/600?random=62",
      modelRight: "https://picsum.photos/400/600?random=63",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 7, m: 15, l: 21, xl: 9, xxl: 3 },
    price: 88,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Breathable", "Moisture-wicking"],
    washing: "Hand wash recommended",
    name: "Devin Booker Suns Jersey",
  },
  {
    _id: "16",
    userId: 116,
    id: 16,
    description: {
      player: "CJ McCollum",
      desc: "Portland Trail Blazers T-shirt, casual",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=64",
      back: "https://picsum.photos/400/600?random=65",
      left: "https://picsum.photos/400/600?random=66",
      right: "https://picsum.photos/400/600?random=67",
      model: "https://picsum.photos/400/600?random=68",
      modelFront: "https://picsum.photos/400/600?random=69",
      modelBack: "https://picsum.photos/400/600?random=70",
      modelLeft: "https://picsum.photos/400/600?random=71",
      modelRight: "https://picsum.photos/400/600?random=72",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 4, s: 9, m: 14, l: 22, xl: 10, xxl: 5 },
    price: 39,
    type: "T-shirt",
    materials: [
      { percentage: 75, materialName: "Cotton" },
      { percentage: 25, materialName: "Polyester" },
    ],
    details: ["Casual fit", "Soft material", "Machine washable"],
    washing: "Machine wash cold",
    name: "CJ McCollum Blazers Tee",
  },
  {
    _id: "17",
    userId: 117,
    id: 17,
    description: {
      player: "Kyrie Irving",
      desc: "Brooklyn Nets Hoodie, warm fleece",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=73",
      back: "https://picsum.photos/400/600?random=74",
      left: "https://picsum.photos/400/600?random=75",
      right: "https://picsum.photos/400/600?random=76",
      model: "https://picsum.photos/400/600?random=77",
      modelFront: "https://picsum.photos/400/600?random=78",
      modelBack: "https://picsum.photos/400/600?random=79",
      modelLeft: "https://picsum.photos/400/600?random=80",
      modelRight: "https://picsum.photos/400/600?random=81",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 3, s: 11, m: 17, l: 23, xl: 13, xxl: 7 },
    price: 74,
    type: "Hoodie",
    materials: [
      { percentage: 60, materialName: "Cotton" },
      { percentage: 40, materialName: "Polyester" },
    ],
    details: ["Soft fleece", "Adjustable hood", "NBA licensed"],
    washing: "Machine wash cold, tumble dry low",
    name: "Kyrie Irving Nets Hoodie",
  },
  {
    _id: "18",
    userId: 118,
    id: 18,
    description: {
      player: "Julius Randle",
      desc: "New York Knicks Jersey, performance",
    },
    gallery: {
      front: "https://picsum.photos/400/600?random=82",
      back: "https://picsum.photos/400/600?random=83",
      left: "https://picsum.photos/400/600?random=84",
      right: "https://picsum.photos/400/600?random=85",
      model: "https://picsum.photos/400/600?random=86",
      modelFront: "https://picsum.photos/400/600?random=87",
      modelBack: "https://picsum.photos/400/600?random=88",
      modelLeft: "https://picsum.photos/400/600?random=89",
      modelRight: "https://picsum.photos/400/600?random=90",
    },
    date_added: Date.now(),
    isPromotion: false,
    sizes: { xs: 2, s: 8, m: 16, l: 22, xl: 8, xxl: 4 },
    price: 86,
    type: "Jersey",
    materials: [{ percentage: 100, materialName: "Polyester" }],
    details: ["Official NBA licensed", "Lightweight", "Moisture-wicking"],
    washing: "Hand wash recommended",
    name: "Julius Randle Knicks Jersey",
  },
];

const ListItemsByTypeSection = () => {
  const allHoodies = allProducts.slice().filter((p) => p.type === "Hoodie");
  const allTshirts = allProducts.slice().filter((p) => p.type === "T-shirt");
  const allJerseys = allProducts.slice().filter((p) => p.type === "Jersey");

  return (
    <div>
      <ItemsLister title="Hoodies" items={allHoodies} />
      <ItemsLister title="T-Shirts" items={allTshirts} />
      <ItemsLister title="Jerseys" items={allJerseys} />
    </div>
  );
};

export default ListItemsByTypeSection;
